services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: stream
      POSTGRES_PASSWORD: stream
      POSTGRES_DB: stream
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql

volumes:
  pgdata-dev:
